# Generated by Django 4.0.2 on 2022-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0042_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='propic',
            field=models.ImageField(blank=True, default='DP.jpg', null=True, upload_to='images'),
        ),
    ]
